### ISSUE TITLE
If vacation message is empty, the save button doesn't save the changes

### ISSUE THREAD

**Issue by pschrafl** [cjeker/qldap_vacation#2]
If the text in the vacation message is empty after the initial placement of the text, the save button doesn't save any changes (text box and checkbox). If the textbox isn't empty, the save button works. It would be great, if this issue could be fixed, as the users might want to delete the vacation message text and uncheck the activation of the vacation message at the same time, it won't save the results due to this bug.

**Comment by cjeker** [comment]
Fixed in a0df6da7aadf15cd320ec53480c5e297c243add1
